[FSTORE-840] Use existing Kafka cluster
logicalclocks/feature-store-api pull request #1028
Opened 2023-05-30 10:00 UTC by bubriks

will need more work in particular for conversion of java config to python and for jks to pem

This PR adds/fixes/changes...
- please summarize your changes to the code 
- and make sure to include all changes to user-facing APIs

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2023-08-23 23:02 UTC, SirOibaf requested changes

2023-08-23 23:02 UTC, SirOibaf commented on python/hsfs/storage_connector.py
> +                ) = client.get_instance()._write_pem(
The external client doesn't have this `_write_pem` file, so the call is going to fail.

2023-08-24 07:16 UTC, bubriks commented on java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/DatasetApi.java
> +    return HopsworksClient.getInstance().handleRequest(new HttpGet(uriString), new BasicResponseHandler());
Yes it this was tested with beam engine, the .jks file was materialized.

2023-08-28 21:28 UTC, SirOibaf approved these changes

2023-08-28 22:23 UTC, merged