[FSTORE-921] Resolve serving key in feature view
logicalclocks/feature-store-api pull request #1059
Opened 2023-06-22 13:22 UTC by kennethmhc

- add `allow_missing` to `get_feature_vector(s)` and return feature vector with missing value 
- fix the logic of required primary key (serving key)

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2023-07-13 09:48 UTC, davitbzh requested changes
See my comments above. Also would be great to add examples how to fetch primary keys in `get_feature_vector` and `get_feature_vectors` docstring examples.

Also I think 1 notebook in load test will be great. You can add the same notebook you sent me

2023-07-13 09:48 UTC, davitbzh commented on python/hsfs/core/vector_server.py
> +        self._feature_vector_col = [feat for feat in features if not feat.label]
`fv.create_training_data()` any flavor of it throws error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-8940fa0ea0cb> in <module>
----> 1 fv1.create_training_data()

/srv/hops/anaconda/envs/theenv/lib/python3.10/site-packages/hsfs/feature_view.py in create_training_data(self, start_time, end_time, storage_connector, location, description, extra_filter, data_format, coalesce, seed, statistics_config, write_options, spine)
    872                 that was launched to create the training dataset.
    873         """
--> 874         td = training_dataset.TrainingDataset(
    875             name=self.name,
    876             version=None,

/srv/hops/anaconda/envs/theenv/lib/python3.10/site-packages/hsfs/training_dataset.py in __init__(self, name, version, data_format, featurestore_id, location, event_start_time, event_end_time, coalesce, description, storage_connector, splits, validation_size, test_size, train_start, train_end, validation_start, validation_end, test_start, test_end, seed, created, creator, features, statistics_config, featurestore_name, id, inode_id, training_dataset_type, from_query, querydto, label, transformation_functions, train_split, time_split_size, extra_filter)
    182             self._label = [feat.name.lower() for feat in self._features if feat.label]
    183             self._extra_filter = filter.Logic.from_response_json(extra_filter)
--> 184         self._vector_server = vector_server.VectorServer(
    185             featurestore_id, features=self._features
    186         )

/srv/hops/anaconda/envs/theenv/lib/python3.10/site-packages/hsfs/core/vector_server.py in __init__(self, feature_store_id, features, training_dataset_version, serving_keys)
     43         self._training_dataset_version = training_dataset_version
     44         self._features = features
---> 45         self._feature_vector_col = [feat for feat in features if not feat.label]
     46         self._prepared_statement_engine = None
     47         self._prepared_statements = None

TypeError: 'NoneType' object is not iterable

2023-07-13 09:48 UTC, davitbzh commented on python/hsfs/core/vector_server.py
>          """Set of primary key names that is used as keys in input dict object for `get_serving_vector` method."""
This is very minor but I guess its better to have `get_feature_vector`

2023-07-13 09:48 UTC, davitbzh commented on python/hsfs/core/vector_server.py
> +            pandas_df.columns = self._feature_vector_col
pandas returns strange column names:
<html><head></head><body>

Training Dataset Feature('id1', 'bigint', 0, False, None, None, 14) | Training Dataset Feature('fg1_id1', 'bigint', 1, False, None, None, 15) | Training Dataset Feature('fg1_id2', 'bigint', 2, False, None, None, 15)
-- | -- | --
6 | 6 | 7

</body></html>

2023-07-13 09:48 UTC, davitbzh commented on python/hsfs/core/vector_server.py
> +            pandas_df.columns = self._feature_vector_col
The same here, column names are strange:
<html><head></head><body>

  | Training Dataset Feature('id1', 'bigint', 0, False, None, None, 14) | Training Dataset Feature('fg1_id1', 'bigint', 1, False, None, None, 15) | Training Dataset Feature('fg1_id2', 'bigint', 2, False, None, None, 15)
-- | -- | -- | --
7 | 7 | 8
6 | 6 | 7

</body></html>

2023-07-13 12:35 UTC, kennethmhc commented
@davitbzh addressed your comment. I will make a PR to the load test.

2023-07-13 13:08 UTC, kennethmhc commented on python/hsfs/feature_view.py
> +        self.init_batch_scoring(training_dataset_version)
bug fix

2023-07-14 12:27 UTC, davitbzh approved these changes

2023-07-14 13:15 UTC, merged