[FSTORE-1190] Attach model to embedding feature
logicalclocks/feature-store-api pull request #1207
Opened 2024-01-30 15:11 UTC by kennethmhc

This PR adds/fixes/changes...
- please summarize your changes to the code 
- and make sure to include all changes to user-facing APIs

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2024-01-30 16:59 UTC, jimdowling approved these changes

2024-02-06 10:58 UTC, javierdlrm requested changes

2024-02-06 10:58 UTC, javierdlrm commented on python/hsfs/embedding.py
> +class HsmlModel:
Same comment as for hopsworks-ee PR. Can we rename it to `ModelVersion`?

2024-02-06 10:58 UTC, javierdlrm commented on python/hsfs/embedding.py
> +            d["hsmlModel"] = HsmlModel.from_model(self.model)
Same comments. "modelVersion"?

2024-02-07 12:22 UTC, javierdlrm approved these changes

2024-02-08 07:57 UTC, merged