[FSTORE-1218] Fix as_of and read_changes doc
logicalclocks/feature-store-api pull request #1216
Opened 2024-02-07 11:11 UTC by marcopellegrinoit

Added banner in as_of and read_changes about the fact that the methods are not available in Python, but only in Spark.

2024-02-07 20:17 UTC, davitbzh requested changes

2024-02-07 20:17 UTC, davitbzh commented on python/hsfs/feature_group.py
> +            HUDI supports Time Travel and Incremental Query via Spark context, exclusively in PySpark/Spark
```suggestion
            Time Travel and Incremental Queries are supported exclusively in PySpark/Spark.
```

2024-02-07 20:17 UTC, davitbzh commented on python/hsfs/feature_group.py
> +            HUDI supports Time Travel and Incremental Query via Spark context, exclusively in PySpark/Spark
```suggestion
            Time Travel and Incremental Queries are supported exclusively in PySpark/Spark.
```

2024-02-07 20:17 UTC, davitbzh commented on python/hsfs/feature_group.py
> -
you still need time travel enabled feature group, but we now also support time_travel_format='DELTA'

2024-02-19 11:10 UTC, vatj approved these changes

2024-02-19 12:26 UTC, merged