[HWORKS-936] Explicit model provenance
logicalclocks/feature-store-api pull request #1238
Opened 2024-02-27 08:25 UTC by o-alex

This PR adds/fixes/changes...
- please summarize your changes to the code 
- and make sure to include all changes to user-facing APIs

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2024-03-15 11:53 UTC, bubriks requested changes

2024-03-15 14:24 UTC, o-alex commented on python/hsfs/core/feature_view_api.py
> +            feature_view_instance: Metadata object of feature view.
copy paste from hsml. sorry. fixed

2024-03-15 14:34 UTC, o-alex commented on python/hsfs/core/explicit_provenance.py
> +                link_json["artifact"]["featurestore_name"],
right about project. and simplified the if else.

2024-03-15 14:35 UTC, o-alex commented on python/hsfs/core/feature_view_engine.py
> +            feature_view_instance: Metadata object of feature view.
fixed

2024-03-18 08:48 UTC, bubriks commented on python/hsfs/core/feature_view_api.py
> +            feature_view_instance: Metadata object of feature view.
fix was not pushed

2024-03-18 15:54 UTC, bubriks commented
use this PR instead: https://github.com/logicalclocks/feature-store-api/pull/1254

2024-03-19 14:08 UTC, closed without merging