[APPEND][FSTORE-1424] Feature logging for spark
logicalclocks/feature-store-api pull request #1367
Opened 2024-07-09 06:43 UTC by kennethmhc

This PR adds/fixes/changes...
- please summarize your changes to the code 
- and make sure to include all changes to user-facing APIs

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2024-07-09 15:02 UTC, manu-sj approved these changes

2024-07-15 09:15 UTC, javierdlrm requested changes

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/core/feature_view_api.py
> +        return _client._send_request("DELETE", path_params, {})
What is this returning? Normally delete methods return void since the corresponding item gets deleted.

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/core/feature_logging.py
> +
Why this method instead of the setter methods for the two fields?  `@transformed_features.setter`  and `@untransformed_features.setter`?

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/core/feature_view_engine.py
>              return feature_logging.untransformed_features
I think these list are not easy to read.
`_get_logging_fg_feature_logging` is returning `features` that can be transformed or untransformed, but the method name indicates `feature_logging`.
`_get_logging_fg` retrieves the `feature_logging` for a `fv` and then call the previous method to return the (transformed or untransformed) features.

I wouldn't guess their behavior based on the method names :)

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/core/feature_view_engine.py
>              return feature_logging.untransformed_features
Actually, based on their used in `log_features`, it seems that `untransformed_features` and `transformed_features` are actually `fg` objects

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/core/feature_view_engine.py
> +            prediction=prediction,
Is `prediction` one or multiple predictions? If many, can we use `predictions` instead?

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/core/feature_view_engine.py
> +        fg = self._get_logging_fg_feature_logging(feature_logging, transformed)
Could we better have a method called `get_feature_group` in the `feature_logging` class, that accepts a `transformed` boolean parameter?
```
def get_feature_group(self, transformed):
    return self._transformed_features if transformed else self._untransformed_features
```

Then:
- we don't need `_get_logging_fg_feature_logging` and `_get_logging_fg `methods. We can just call `get_feature_logging` from the engine and then the internal method if needed.
- we don't need to pass `feature_logging` as a separate parameter. We can use `get_feature_logging(fv)`.get_feature_group(transformed)

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/core/feature_view_engine.py
> +    def log_features(self, fv, feature_logging, features_rows, prediction=None, transformed=False, write_options=None, training_dataset_version=None, hsml_model=None):
Can we add the types for all these parameters?
What is the type of `feature_rows`?

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/engine/python.py
> +    def get_feature_logging_df(features,
Can we add types to all parameters?

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/engine/spark.py
> +                               **kwargs):
Can we add types to these parameters?

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/engine/spark.py
> +                                       lit(training_dataset_version).cast(LongType()))
Indentation seems off here.

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/engine/spark.py
> +                                       lit(now).cast(TimestampType()))
Indentation here as well

2024-07-15 09:15 UTC, javierdlrm commented on python/hsfs/feature_view.py
> +            self._feature_logging = self._feature_view_engine.get_feature_logging(self)
What if `delete_log` is called in a new FV without feature_logging enabled? (no call to `enable_feature_logging()` or `log()`) ?
I guess this line will return None, and then fail in the `delete_feature_logs()` ?

2024-07-15 09:54 UTC, kennethmhc commented
@javierdlrm will close this PR and made a new one to the hopswork-api repo

2024-07-15 09:54 UTC, closed without merging