add Databricks configuration documentation
logicalclocks/feature-store-api pull request #149
Opened 2020-11-15 23:45 UTC by SirOibaf

2020-11-15 23:45 UTC, SirOibaf commented
I need to add some images.

2020-11-16 08:44 UTC, moritzmeister requested changes
few typos and grammar changes

2020-11-16 08:44 UTC, moritzmeister commented on docs/integrations/databricks.md
> +Users can register a new Databricks instance by navigating the the `Integrations` tab of a project Feature Store. Registering a Databricks instance requires adding a the instance address and the API
```suggestion
Users can register a new Databricks instance by navigating to the `Integrations` tab of a project Feature Store. Registering a Databricks instance requires adding the instance address and the API Key.
```

2020-11-16 08:44 UTC, moritzmeister commented on docs/integrations/databricks.md
> +The API Key will be stored in the Hopsworks secret store for the user and will be available only for that user.  If multiple users need to configure Databricks clusters, each has to generate an API K
```suggestion
The API Key will be stored in the Hopsworks secret store for the user and will be available only for that user.  If multiple users need to configure Databricks clusters, each has to generate an API Key and register an instance. The Databricks instance registration does not have a project scope, meaning that once registered, the user can configure clusters for all projects they are part of.
```

2020-11-16 08:44 UTC, moritzmeister commented on docs/integrations/databricks.md
> +- Upload to DBFS an archive containing the necessary Jars for HSFS and HopsFS to be able to read and write from the Hopsworks Feature Store
```suggestion
- Upload an archive to DBFS containing the necessary Jars for HSFS and HopsFS to be able to read and write from the Hopsworks Feature Store
```

2020-11-17 13:03 UTC, moritzmeister approved these changes

2020-11-17 13:04 UTC, merged