Online-fs Kafka ingestion
logicalclocks/feature-store-api pull request #238
Opened 2021-02-05 13:43 UTC by moritzmeister

2021-03-30 12:59 UTC, SirOibaf requested changes

2021-03-30 12:59 UTC, SirOibaf commented on python/hsfs/feature_group.py
> +        features=[],
Revert to none to avoid static lists.

2021-04-01 09:40 UTC, moritzmeister commented on python/hsfs/feature_group.py
> +        features=[],
fixed

2021-04-01 12:52 UTC, SirOibaf approved these changes

2021-04-01 12:52 UTC, merged