[HOPSWORKS-2071][append] Data validation hsfs docs
logicalclocks/feature-store-api pull request #241
Opened 2021-02-12 08:58 UTC by tkakantousis

2021-02-12 14:28 UTC, moritzmeister requested changes
some minor spelling and typos

2021-02-12 14:28 UTC, moritzmeister commented on docs/templates/feature_validation.md
> +    // Create an expectation for the "salary" and "commissio" features so that their min value is "10" and their max is "100"
```suggestion
    // Create an expectation for the "salary" and "commission" features so that their min value is "10" and their max is "100"
```

2021-02-12 14:28 UTC, moritzmeister commented on docs/templates/feature_validation.md
> +Raw data being ingested into the feature store maybe suffer from incorrect or corrupt values, may need to be validated
```suggestion
Raw data being ingested into the feature store might suffer from incorrect or corrupt values, and may need to be validated
```

2021-02-12 14:28 UTC, moritzmeister commented on docs/templates/feature_validation.md
> +validation is part of the HSFS Java/Scala and Python API for working with Feature Groups. Users work with the abstractions:
```suggestion
validation as part of the HSFS Java/Scala and Python API for working with Feature Groups. Users work with the following abstractions:
```

2021-02-12 17:59 UTC, tkakantousis commented
I forgot the API reference, will add it

2021-02-15 16:54 UTC, tkakantousis commented
Done with changes

2021-02-17 09:54 UTC, moritzmeister approved these changes

2021-02-17 09:57 UTC, merged