[HOPSWORKS-2617] add batch lookup API to retrieve batch of serving vectors from online feature store
logicalclocks/feature-store-api pull request #383
Opened 2021-06-17 18:19 UTC by davitbzh

2021-07-13 08:38 UTC, moritzmeister requested changes
I don't see where the auto commit is disabled in the JAVA api and where the transactions are started. Does it work differently with the Java JDBC api than with SQLalchemy or is it missing?

2021-07-13 08:38 UTC, moritzmeister commented on python/hsfs/core/training_dataset_engine.py
> +        _transaction.commit()
looks duplicated, that's handled better in the java part I believe

2021-07-19 07:20 UTC, davitbzh commented
> I don't see where the auto commit is disabled in the JAVA api and where the transactions are started. Does it work differently with the Java JDBC api than with SQLalchemy or is it missing?

it is disabled here: https://github.com/davitbzh/feature-store-api/blob/get_serving_vectors/java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java#L207
and its started here https://github.com/davitbzh/feature-store-api/blob/get_serving_vectors/java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java#L242
this is how I understood JAVA api is handling it

2021-11-01 09:45 UTC, moritzmeister approved these changes

2021-11-01 10:13 UTC, merged