[DOCS] Fixes for databricks integration documentation
logicalclocks/feature-store-api pull request #462
Opened 2021-09-08 12:56 UTC by maismail

2021-09-08 13:21 UTC, berthoug requested changes

2021-09-08 13:21 UTC, berthoug commented on docs/integrations/databricks/api_key.md
> +As secret name, enter *hopsworks/role/[MY_DATABRICKS_ROLE]* replacing [MY_DATABRICKS_ROLE] with the AWS role you have created in [Step 1](#step-1-create-an-instance-profile-to-attach-to-your-databric
```suggestion
As secret name, enter *hopsworks/role/[MY_DATABRICKS_ROLE]* replacing [MY_DATABRICKS_ROLE] with the AWS role you have created in [Step 1](#step-1-create-an-instance-profile-to-attach-to-your-databricks-clusters). Select next twice and finally store the secret.
```

2021-09-08 13:21 UTC, berthoug commented on docs/integrations/databricks/networking.md
> +The virtual network peering will allow full access between the Hopsworks virtual network and the Databricks virtual network by default. However, if you have a different setup, ensure that the *Networ
```suggestion
The virtual network peering will allow full access between the Hopsworks virtual network and the Databricks virtual network by default. However, if you have a different setup, ensure that the *Network Security Group* of the Feature Store is configured to allow traffic from your Databricks clusters.
```

2021-09-09 09:55 UTC, moritzmeister approved these changes

2021-09-09 09:57 UTC, berthoug approved these changes

2021-09-09 09:58 UTC, merged