[HOPSWORKS-2955] default `train_split` property to "train"
logicalclocks/feature-store-api pull request #562
Opened 2022-01-28 13:57 UTC by davitbzh

2022-01-29 13:18 UTC, jimdowling approved these changes

2022-01-31 14:41 UTC, moritzmeister approved these changes

2022-02-01 08:47 UTC, SirOibaf requested changes
PR breaks in the backend.

2022-02-02 10:43 UTC, moritzmeister commented on python/hsfs/core/training_dataset_engine.py
> +            Warning(
don't you have to use the python `warnings.warn()`?

2022-02-04 10:20 UTC, moritzmeister approved these changes

2022-02-04 10:43 UTC, merged