train_split_train
logicalclocks/feature-store-api pull request #563
Opened 2022-01-28 14:03 UTC by davitbzh

2022-01-29 13:18 UTC, jimdowling approved these changes

2022-02-01 08:44 UTC, SirOibaf requested changes
This PR breaks in the backend.

2022-02-04 10:21 UTC, moritzmeister commented
@davitbzh can you adjust this PR also, the same as for the master branch one?

2022-02-04 10:43 UTC, moritzmeister approved these changes

2022-02-04 10:45 UTC, SirOibaf approved these changes

2022-02-04 10:45 UTC, merged