[HOPSWORKS-3010] add bigquery connector
logicalclocks/feature-store-api pull request #610
Opened 2022-04-05 15:34 UTC by DhananjayMukhedkar

add bigquery connector-init

2022-04-25 08:01 UTC, moritzmeister requested changes

2022-04-25 08:01 UTC, moritzmeister commented on python/hsfs/storage_connector.py
> +            path = query
same here

2022-04-28 15:35 UTC, DhananjayMukhedkar commented on docs/templates/api/storage_connector_api.md
> +
I added some general information in the header page, and details on using the read method in the API docstring. Let me know if it works.

2022-05-02 07:34 UTC, moritzmeister approved these changes

2022-05-06 07:55 UTC, merged