[HOPSWORKS-3054] Stream Feature Group Python Engine ingestion
logicalclocks/feature-store-api pull request #635
Opened 2022-05-13 16:14 UTC by moritzmeister

2022-05-17 08:57 UTC, SirOibaf requested changes
Some high level questions:
- I thought we agreed on setting `stream=True` for all the feature group created using the Python engine. I don't see it but maybe I missed in a previous PR.
- The `insert_stream` Python method still throws a NotImplementedException. Should we leave it like this? I guess so.
- There is a `python/test.py` file hanging around at the bottom of the PR. Should we remove it?

2022-05-17 09:32 UTC, moritzmeister commented on python/hsfs/client/base.py
> +        return os.path.join("/tmp", "client_key.pem")
How can he "request" it? I thought we said we are moving away from the cert folder and always put it in `tmp`

2022-05-17 09:32 UTC, moritzmeister commented on python/hsfs/engine/python.py
> +    pass
just if you uninstall it manually.

2022-05-17 09:33 UTC, moritzmeister commented on python/hsfs/engine/python.py
> +        job = self._job_api.get(job_name)
I thought it's nice to return the job anyway, even when you are not starting it immediately, then later, they can use hopsworks-api to start it and they know the name of the job etc.

2022-05-18 21:38 UTC, SirOibaf approved these changes

2022-05-19 07:13 UTC, merged