[HOPSWORKS-3103][HOPSWORKS-3161] Improve hive error message
logicalclocks/feature-store-api pull request #656
Opened 2022-06-03 06:02 UTC by kennethmhc

2022-06-06 21:36 UTC, SirOibaf requested changes

2022-06-06 21:36 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
> +              "It is possible to request access from admins of '%s'.", featureStore, featureStore));
We don't use "project admins" as a concept, we use "data owner". Let's be consistent here so that users don't get confused.

2022-06-06 21:36 UTC, SirOibaf commented on python/hsfs/engine/python.py
> +                    f" It is possible to request access from admins of '{feature_store}'."
Same "project admin" comment as above.

2022-06-08 02:26 UTC, kennethmhc commented on java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
> +        if (matcher.find()) {
I think it is good to have because if the name/format of hive db changes or reasons, `matcher.group(1)` will throw exception.

2022-06-09 16:54 UTC, SirOibaf approved these changes

2022-06-09 16:54 UTC, merged