[FSTORE-328] throw intelligible error message if user set primary and partition keys doesn't exist
logicalclocks/feature-store-api pull request #804
Opened 2022-09-28 23:05 UTC by davitbzh

This PR adds/fixes/changes...
- please summarize your changes to the code 
- and make sure to include all changes to user-facing APIs

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2022-09-30 15:04 UTC, moritzmeister requested changes
Please write unit tests.

2022-10-10 22:07 UTC, SirOibaf requested changes
Add Java tests as well please

2022-10-14 12:36 UTC, SirOibaf commented on java/src/test/java/com/logicalclocks/hsfs/TestFeatureGroup.java
> + *  Copyright (c) 2022. Logical Clocks AB
Hopsworks AB

2022-10-23 17:07 UTC, SirOibaf requested changes

2022-10-23 17:07 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupUtils.java
> +                                      List<Feature> features) throws FeatureStoreException {
I think this method has 2 problems:
- The code is condensed in a single method, but we need to call the method 4 times to validate all the input parameters. I think we can do the validation in a single pass.
- The method is using strings and things being null for the method to have different behaviors. This is usually a recipe for disaster. Someone somewhere will call this method with the wrong parameters and either won't fully validate the feature group or the method will blow up.

I think we should either break down the method in 4 different methods, or do the validation in a single step. I prefer the second.

2022-10-23 17:07 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/engine/ExternalFeatureGroupEngine.java
> +    utils.verifyAttributeKeyNames("primary", externalFeatureGroup.getPrimaryKeys(),
External feature groups can also have event time.

2022-10-23 17:07 UTC, SirOibaf commented on python/hsfs/util.py
> +def verify_attribute_key_names(attribute_name, provided_names, features):
Same comment as for the java method. The method has all the code but needs to be called several times to fully validate the feature group.

2022-10-23 17:07 UTC, SirOibaf commented on python/hsfs/core/external_feature_group_engine.py
> +        )
Same comment as for the java part - external feature groups can also have event time columns

2022-10-28 11:58 UTC, moritzmeister requested changes

2022-10-28 11:58 UTC, moritzmeister commented on java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupUtils.java
> +
```suggestion
```

2022-10-28 11:58 UTC, moritzmeister commented on python/hsfs/util.py
> +    feature_names = set([feat.name for feat in feature_group_obj.features])
```suggestion
    feature_names = set(feat.name for feat in feature_group_obj.features)
```
unnecessary to convert between the two

2022-10-28 11:58 UTC, moritzmeister commented on python/hsfs/util.py
> +        diff = list(set(feature_group_obj.primary_key) - feature_names)
```suggestion
        diff = set(feature_group_obj.primary_key) - feature_names
```

2022-10-28 11:58 UTC, moritzmeister commented on python/hsfs/util.py
> +        diff = list(set(feature_group_obj.partition_key) - feature_names)
```suggestion
        diff = set(feature_group_obj.partition_key) - feature_names
```

2022-10-31 13:55 UTC, moritzmeister approved these changes

2022-10-31 17:01 UTC, moritzmeister commented
@davitbzh please rebase on master so that unit tests pass.

2022-11-01 09:01 UTC, SirOibaf approved these changes

2022-11-01 09:01 UTC, merged