[FSTORE-332] implement method for get_or_create_feature_view
logicalclocks/feature-store-api pull request #813
Opened 2022-10-03 15:32 UTC by davitbzh

This PR adds/fixes/changes...
- added get_or_create_feature_view method

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [x] Unit Tests
- [ ] Integration Tests
- [] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2022-10-04 11:48 UTC, kennethmhc requested changes

2022-10-04 11:48 UTC, kennethmhc commented on python/hsfs/feature_store.py
> +            if (
can reuse `create_feature_view` here.

2022-10-04 11:48 UTC, kennethmhc commented on java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
> +  public FeatureView getOrcreateFeatureView(String name, Query query, Integer version, String description,
```suggestion
  public FeatureView getOrCreateFeatureView(String name, Query query, Integer version, String description,
```

2022-10-04 11:48 UTC, kennethmhc commented on java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
> +  public FeatureView getOrcreateFeatureView(String name, Integer version) throws FeatureStoreException, IOException {
`Query` is compulsory for creating a fv, need to include in the parameter as well.

2022-10-04 11:48 UTC, kennethmhc commented on java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureViewApi.java
> +  public FeatureView getOrCreateFeatureView(FeatureStore featureStore, String name, Integer version,  Query query,
This should be in `FeatureViewEngine`

2022-10-12 06:44 UTC, kennethmhc requested changes

2022-10-12 06:44 UTC, kennethmhc commented on java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
> +        featureView = new FeatureView(name, version, query, description, featureStore, labels);
This does not save fv in the backend, either using a builder or move this part to `FeatureStore` and reuse `FeatureStore.createFeatureView`.

2022-10-13 23:03 UTC, davitbzh commented on python/hsfs/feature_store.py
> +        version: int,
This is to be compatible with `get_or_create_feature_group`. There version is required. we agreed that  for `get_or_create` methods versions are required

2022-10-14 15:58 UTC, kennethmhc commented on java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
> +            .name(name)
`description` is missing.

2022-10-15 17:01 UTC, davitbzh commented on java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
> +            .name(name)
ahh, thanks. good catch

2022-10-19 12:02 UTC, kennethmhc approved these changes
LGTM!

2022-10-19 14:37 UTC, merged