Improved documentation
logicalclocks/feature-store-api pull request #858
Opened 2022-11-09 20:22 UTC by Maxxx-zh

2022-11-11 14:22 UTC, davitbzh requested changes

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +            ```
define `feature_view`

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
define `feature_view`

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
the same here

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
define feature_view

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
define `feature_view`

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
the same here

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
define `feature_view`

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
add here time series split as well

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/transformation_function.py
> +
define

2022-11-11 14:22 UTC, davitbzh commented on python/hsfs/transformation_function.py
> +
define

2022-11-15 23:28 UTC, davitbzh requested changes

2022-11-15 23:28 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
we do support string, and datetime objects please use either of them. This is too complex.

2022-11-17 10:17 UTC, davitbzh commented on python/hsfs/feature_view.py
> +                write_options={"wait_for_job": False}
add comments also so its easier for the user to follow. Explain and show what the difference between `{"wait_for_job": False}` and `{"wait_for_job": True}`

2022-11-17 10:19 UTC, davitbzh commented on python/hsfs/feature_view.py
> +            end_time = int(float(datetime.strptime("2022-06-04 23:59:59", date_format).timestamp()) * 1000)
use simpler date formats. For example just string `2022-05-01` works now. Also python datetime objects works as well

2022-11-17 10:21 UTC, davitbzh commented on python/hsfs/feature_view.py
> +                    write_options = {'wait_for_job': True},
again show or explain difference between `{'wait_for_job': True}` and `{'wait_for_job': False}`

2022-11-17 10:21 UTC, davitbzh commented on python/hsfs/feature_view.py
> +                    data_format = "csv",
mention also other file formats we support. You can mention this in comment

2022-11-17 10:22 UTC, davitbzh commented on python/hsfs/feature_view.py
> +                    description = 'transactions fraud online training dataset jan/feb',
generally try to add more general names and descriptions in these snippets

2022-11-17 10:31 UTC, davitbzh commented on python/hsfs/feature_view.py
> +            X_train, X_val, X_test, y_train, y_val, y_test = feature_view.train_validation_test_split(
```suggestion
            # get  feature view instance for the feature store 
            feature_view = ...
            # create and fetch training dataset
            X_train, X_val, X_test, y_train, y_val, y_test = feature_view.train_validation_test_split(
```

2022-11-17 10:39 UTC, davitbzh commented on python/hsfs/feature_view.py
> +            feature_view.delete_training_dataset_tag(
```suggestion
            # get freature store instance 
            fs = ...
            # get feature feature view object 
            feature_view = fs.get_feature_view(...)
            # delete training dataset tag
            feature_view.delete_training_dataset_tag(
```

2022-11-21 09:32 UTC, davitbzh commented on python/hsfs/feature_store.py
> +        Then the transformation functions are applied when you read training data, read batch data, or get feature vectors.
`value is online transformation function name` this is not true it must be `value is online transformation function instance`

2022-11-21 09:55 UTC, davitbzh commented on python/hsfs/feature_view.py
> +                test_size=0.2,
if you are using event time split then this is not necessary. Is this even working?

2022-11-21 10:01 UTC, davitbzh commented on python/hsfs/feature_view.py
> +
can you please also add example and explanation of `feature_group.insert(df, write_options={"wait_for_job" : False})`

2022-11-21 10:03 UTC, davitbzh commented on python/hsfs/feature_view.py
> +            ```python
there are serval examples of this. You don't need to warn about this to user every time. Just once will be fine

2022-11-22 09:49 UTC, davitbzh commented on python/hsfs/transformation_function.py
> +
also show this for custom transformation functions

2022-11-22 09:50 UTC, davitbzh commented on python/hsfs/feature_store.py
> +        Then the transformation functions are applied when you read training data, read batch data, or get feature vectors.
```suggestion
        Then the transformation functions are applied when you read training data, get batch data, or get feature vectors.
```

2022-11-23 21:11 UTC, davitbzh approved these changes

2022-11-24 05:19 UTC, jimdowling requested changes

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +            # recreate a training dataset
# recreate a training dataset that has been deleted

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +            feature_df, label_df = feature_view.training_data(
features_df, labels_df = ...

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +            feature_df, label_df = feature_view.training_data(
features_df, labels_df = ...

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
>          !!! info
This info box is duplicated. Please remove it - it's already in the above section on recreating training datasets.

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +        !!! example "Create random splits"
example "Create random train/test splits"

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +        !!! example "Create time-series based splits"
Create time-series train/test splits

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
>          !!! info
Again, remove this info box, please.

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
>          !!! info
Please remove this info box from all the places it is duplicated in this file. There's like 7 places in this file with the same info box.

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
>          !!! info
remove

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +            feature_df, label_df = feature_view.get_training_data(training_dataset_version=1)
Change everywhere to 
features_df
and
labels_df

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +            feature_view.get_training_dataset_tag(
tag_str = feature_view.get_training_dataset_tag(
....)

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
> +            feature_view.get_training_dataset_tags(
list_tags = ...

2022-11-24 05:19 UTC, jimdowling commented on python/hsfs/feature_view.py
>      def purge_training_data(self, version: int):
Here we are calling it 'version'.
But it's "training_dataset_version" everywhere else, right?

2022-11-24 05:24 UTC, jimdowling requested changes

2022-11-24 05:24 UTC, jimdowling commented on python/hsfs/constructor/query.py
> +            query = fg1.join(fg2)
This code is incorrect, right? The join() method is defined on a query object, not a FG.
It could be:
 query = fg1.select_all().join(fg2)

2022-11-24 05:24 UTC, jimdowling commented on python/hsfs/constructor/query.py
> +            feature_join = fg1.join(fg2)
Let's call it query, not 'feature_join'. To be consistent.

query = feature_join = fg1.select_all().join(fg2)

2022-11-24 05:24 UTC, jimdowling commented on python/hsfs/constructor/query.py
> +            feature_join = fg1.select_all()
query =  = fg1.select_all()

2022-11-24 05:24 UTC, jimdowling commented on python/hsfs/constructor/query.py
> +            query = fg1.join(fg2)
query = fg1.select_all().join(fg2)

2022-11-24 05:24 UTC, jimdowling commented on python/hsfs/constructor/query.py
> +            query = fg1.join(fg2)
query = fg1.select_all().join(fg2)

2022-11-24 05:24 UTC, jimdowling commented on python/hsfs/feature_store.py
> +            fs.get_transformation_functions()
Add the return type

2022-11-24 05:24 UTC, jimdowling commented on python/hsfs/feature_store.py
> +            fs.get_transformation_functions()
Like, 
list_transformation_fns =

2022-11-24 16:48 UTC, jimdowling reviewed
Will this change
version -> training_dataset_version
break existing clients?

2022-11-24 17:44 UTC, jimdowling commented
There's still a bunch of my comments to address
 @Maxxx-zh

2022-11-28 04:52 UTC, jimdowling approved these changes
LGTM

2022-11-29 10:23 UTC, merged