[FSTORE-618] Expand current java docstrings to cover new hsfs functionalities
logicalclocks/feature-store-api pull request #932
Opened 2023-02-14 21:11 UTC by davitbzh

This PR adds/fixes/changes...
- please summarize your changes to the code 
- and make sure to include all changes to user-facing APIs

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2023-02-20 12:32 UTC, moritzmeister requested changes
It looks a lot, but I did the hard part and added eveything with suggestions so you can commit it directly.

A few of the things are comments, I am for example not sure if we should put the proper return types?

2023-02-20 12:33 UTC, moritzmeister requested changes
It looks a lot, but I did the hard part and added eveything with suggestions so you can commit it directly.

A few of the things are comments, I am for example not sure if we should put the proper return types?

2023-02-20 20:50 UTC, davitbzh commented on java/src/main/java/com/logicalclocks/hsfs/FeatureView.java
> +   *                               dataset.
we don't use transformation functions in Java client. If there is transformation function attached it will fail

2023-02-21 14:15 UTC, davitbzh commented on java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
> +   *        FeatureGroup fg = fs.getOrCreateFeatureGroup("fg_name", 1);
there is `build()`

2023-03-01 22:16 UTC, SirOibaf commented
@davitbzh - Can we remove this class: https://github.com/logicalclocks/feature-store-api/blob/master/java/src/main/java/com/logicalclocks/hsfs/MainClass.java? It just a prototype and it's showing up in the documentation. I think we should remove it.

2023-03-01 22:57 UTC, SirOibaf requested changes

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
> +   * @param saveMode com.logicalclocks.hsfs.saveMode: Append, Overwrite, ErrorIfExists, Ignore
This is wrong. `SaveMode` is from the `org.apache.spark.sql` package. What was there was correct.

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * Reads the feature group by from the offline storage as Spark DataFrame on Hopsworks and Databricks.
I don't see why we need to mention `Databricks` here. Seems like this was done on all the methods. Please remove it.

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   *        fg.read()
Since we are adding the snippets, we should do it properly and have the actual code not some random `...`

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * Persist the metadata and materialize the feature group to the feature store or insert data from a dataframe into
This first sentence is a bit hard to read. It's also explained a bit later in the documentation that if the feature group doesn't exists the metadata is created, so I'm not sure we need this first sentence. 

Same applies to all the other `insert()` variations.

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * `onlineEnabled=true`. To insert only into the online storage, set `storage="online"`, or oppositely
This is wrong, it's not Python :) The code snippet is correct, you need the enum to specify which storage to write to, not the string.

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * `onlineEnabled=true`. To insert only into the online storage, set `storage="online"`, or oppositely
Same as above.

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * `onlineEnabled=true`. To insert only into the online storage, set `storage="online"`, or oppositely
Same

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * `onlineEnabled=true`. To insert only into the online storage, set `storage="online"`, or oppositely
Same

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * `onlineEnabled=true`. To insert only into the online storage, set `storage="online"`, or oppositely
Same

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
> +   * `onlineEnabled=true`. To insert only into the online storage, set `storage="online"`, or oppositely
Same

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
> +   * the data into a Spark DataFrame or use the `Query`-API to perform joins between feature groups and create feature
I have 2 problems with this sentence: 
- The metadata handle doesn't just let you read the data into a Spark DataFrame, it lets you interact with the feature group, i.e. you can write it as well.
- Even if there are code paths that let you get back a Spark DataFrame, I would not mention it on the FeatureStore object documentation, which is most likely going to stay the same when we'll have multiple implementations (Flink, ...)

2023-03-01 22:57 UTC, SirOibaf commented on java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
> +   * <p>Getting a feature group from the Feature Store means getting its metadata handle so you can subsequently read
Same

2023-03-09 16:08 UTC, SirOibaf approved these changes

2023-03-09 16:13 UTC, moritzmeister approved these changes

2023-03-09 16:14 UTC, merged