[FSTORE-646][FSTORE-644] Bigquery and GCS add validation for python support
logicalclocks/feature-store-api pull request #992
Opened 2023-04-28 12:58 UTC by DhananjayMukhedkar

This PR adds/fixes/changes...
- please summarize your changes to the code 
- and make sure to include all changes to user-facing APIs

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2023-05-03 07:40 UTC, bubriks reviewed
Just some minor comments

2023-05-03 07:40 UTC, bubriks commented on python/hsfs/storage_connector.py
> +        ):
Maybe this is cleaner
```suggestion
        if not engine.get_instance().is_connector_type_supported(self.type):
```

2023-05-03 07:40 UTC, bubriks commented on python/hsfs/storage_connector.py
> +        if not engine.get_instance().is_connector_type_supported(StorageConnector.GCS):
Maybe this is cleaner
```suggestion
        if not engine.get_instance().is_connector_type_supported(self.type):
```

2023-05-05 09:30 UTC, DhananjayMukhedkar commented
Cover three JIRAs. They are not mutually related

- https://hopsworks.atlassian.net/browse/FSTORE-647
- https://hopsworks.atlassian.net/browse/FSTORE-644
- https://hopsworks.atlassian.net/browse/FSTORE-646

2023-05-11 14:07 UTC, bubriks requested changes
some minor comments, but only duplication is an issue

2023-05-23 08:41 UTC, merged